// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu_Wiv3DIdEedhqj3oePvbJTOW6vslCJM',
    appId: '1:473185453950:web:e6ceac8b7f03a2a12e552f',
    messagingSenderId: '473185453950',
    projectId: 'gradly-661dd',
    authDomain: 'gradly-661dd.firebaseapp.com',
    storageBucket: 'gradly-661dd.firebasestorage.app',
    measurementId: 'G-SWGX42DGQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_w8wt2ZjDjw_R6WEj7UQZfsDb0hzUin8',
    appId: '1:473185453950:android:0435567d544584bc2e552f',
    messagingSenderId: '473185453950',
    projectId: 'gradly-661dd',
    storageBucket: 'gradly-661dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDYciDeuI2q6S9SzBhkFcOE28hDRFpwgw',
    appId: '1:473185453950:ios:7d27556271969f7d2e552f',
    messagingSenderId: '473185453950',
    projectId: 'gradly-661dd',
    storageBucket: 'gradly-661dd.firebasestorage.app',
    iosBundleId: 'com.example.gradly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDYciDeuI2q6S9SzBhkFcOE28hDRFpwgw',
    appId: '1:473185453950:ios:7d27556271969f7d2e552f',
    messagingSenderId: '473185453950',
    projectId: 'gradly-661dd',
    storageBucket: 'gradly-661dd.firebasestorage.app',
    iosBundleId: 'com.example.gradly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu_Wiv3DIdEedhqj3oePvbJTOW6vslCJM',
    appId: '1:473185453950:web:c8fa1d864a5407f12e552f',
    messagingSenderId: '473185453950',
    projectId: 'gradly-661dd',
    authDomain: 'gradly-661dd.firebaseapp.com',
    storageBucket: 'gradly-661dd.firebasestorage.app',
    measurementId: 'G-VQ8KLXWTRJ',
  );
}
